### ISSUE TITLE
Transition model metadata

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/GeoPose#1]
Issue was raised in 12.02.21 meeting regarding interpolation of poses in support of WebXR video streams.  This is an important use case and should be supported. The sense of the original discussion (according to my notes anyway) was that we recognized that a consumer of a GeoPose sequence might want to compute intermediate poses and that a producer might know if that were possible. We also recognized that the specification of *how* to compute intermediate GeoPoses was in itself complex and we postponed and supporting detail beyond the two choices "none" and "interpolate" to a later version.

**Comment by 3DXScape** [comment]
My rationale:

Poses always represent the location and orientation of a real or virtual physical entity. There is temporal continuity of pose for any such entity. On the other hand, there is no condition on consecutive poses in a sequence. 

There are two causes: 

- First, the poses themselves may be representative of a physical object only at the instant assigned to the pose. Consider a service that provides a sequence of predicted timed poses of a camera that would observe a satellite flare (specular reflection of sunlight) for a specific satellite at a specific earth location. Poses between the member poses of the sequence are meaningless. 

- Second, the sampling of poses may not support computation of intermediate poses. Consider poses that are sampled at a rate much slower than the rate of change of the pose of an underlying externally controlled (such as an airplane controlled by a pilot) physical entity. The sampled poses do not constrain or otherwise provide computational control for estimating intermediate poses. Alternatively, the provider of the sequence may declare via metadata whether it is possible and/or reasonable to compute intermediate poses. The provider is in a position to know this information, which may be binary: "none" => the data do not support the computation of intermediate poses or "interpolate" => the data do support the computation of intermediate poses - though the method is not prescribed. These are the two values currently in the enumeration in the Logical Model TransitionModel datatype. 

I know from my experience with the "fair fight" issue in distributed simulations that there are a lot of possibilities in defining how to interpolate and these are themselves as complex as GeoPose. I support postponing definition of more comprehensive metadata to a later version but leaving this as an enumeration that we can expand to include additional possibilities beyond the binary "none" and "interpolate". I believe that the "interpolate" choice supports the WebXR use case but would also support an additional enumeration member "WebXR" or something similar to indicate that the sequence follows the WebXR specification/expectations.

**Comment by rjksmith** [comment]
@3DXScape Thanks for your feedback and explanation of the GeoPose rationale.

I raised this issue in relation to [WebVMT](https://w3c.github.io/sdw/proposals/geotagging/webvmt/) as I was unable to find a description of how interpolation is handled in the [GeoPose spec](https://github.com/opengeospatial/GeoPose/tree/main/standard). It would be helpful to list the possible values of `TransitionModel` with a description of its possible values and their meanings.

I'll raise my use case as a separate issue as I don't want to detract from this discussion.

Hope this helps.

**Comment by 3DXScape** [comment]
Sorry, I meant WebVMT not WebXR when I raised the issue. The TransitionModel is an enumeration and the values are in the figure on page 27 of the current PDF document. It would be helpful to add informative text describing the members of the enumeration. My suggestion then morphs to a question of adding one or more WebVMT values to the enumeration and if so, what they should be. I think the idea of a pose stream synchronized to a video stream is extremely valuable.

**Comment by 3DXScape** [comment]
I assigned the issue to you. If you don't want it, send it back :-)

**Comment by rjksmith** [comment]
> Sorry, I meant WebVMT not WebXR when I raised the issue. The TransitionModel is an enumeration and the values are in the figure on page 27 of the current PDF document. It would be helpful to add informative text describing the members of the enumeration. My suggestion then morphs to a question of adding one or more WebVMT values to the enumeration and if so, what they should be. I think the idea of a pose stream synchronized to a video stream is extremely valuable.

No problem. You're right - I overlooked this on page 27. It would be helpful to add some informative text.

WebVMT currently supports [linear, step and no interpolation](https://github.com/webvmt/community-group/issues/2) schemes which are designed to align with [OGC Moving Features](https://www.ogc.org/standards/movingfeatures).

**Comment by rjksmith** [comment]
[WebVMT use case](https://github.com/opengeospatial/GeoPose/issues/2) raised

**Comment by 3DXScape** [comment]
Updated the shemata but have not changed the informative text to explain this. Work in progress.

**Comment by 3DXScape** [comment]
Same status: schemata/instance examples updated but haven't had time to work on text.

**Comment by 3DXScape** [comment]
Text still needs to be updated.

**Comment by 3DXScape** [comment]
No further discussion so closing. Standard draft reflect the discussion.
