### ISSUE TITLE
Data sets for GeoPose

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPose#13]
Last week Nazih sent a message to the GeoPose mailing list asking if anyone is aware of any data sets that could be useful for testing in GeoPose compliance or development efforts. 

During the meeting on Friday April 23, @3DXScape reminded us that he has set up HTTP://geopose.io for purpose of providing services. He also provided a link to the [Solar GeoPose validator](https://service.geopose.io/solar/swagger/index.html) and to the [explanation page](https://geopose.io/geoposeinfo/index.html) 

In addition, @jmorely volunteered to look into having a data set prepared with GeoPose based on some autonomous driving data sets in Ordnance Survey.

Recently, @jvinje identified [the 4 Seasons Dataset and service](https://www.4seasons-dataset.com/) that also seems highly relevant (and planetary in scale).

If you are aware of any other data sets that could be used or adapted for GeoPose validation or examples, please post them to this issue. Thank you!

**Comment by ghobona** [comment]
@cperey @3DXScape Please consider submitting a title and abstract for module on GeoPose for the June 2021 Developer Track session. Your could, for example, design a training module around the validator and sample datasets.

[20210616_Developer_Track_Call_for_Instructors.pdf](https://github.com/opengeospatial/GeoPose/files/6531470/20210616_Developer_Track_Call_for_Instructors.pdf)

**Comment by 3DXScape** [comment]
Comments have been acted on. Data sets are in the repo and GeoPose will participate in the June Developer Track session.
