### ISSUE TITLE
Exploration of Possible OGC/non-OGC GeoPose APIs

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPose#15]
During meeting on April 30, Josh raised topic of an API for GeoPose.  In the Open AR Cloud, there is a repo that contains preliminary API for GeoPose. 

Please visit https://github.com/OpenArCloud/oscp-geopose-protocol

Discuss in this topic and feel free to post in the OSCP Open Source GeoPose also. Thank you!

**Comment by 3DXScape** [comment]
Will discuss on 16 June meeting.

**Comment by 3DXScape** [comment]
Scoped for later. Closed for now.
