### ISSUE TITLE
Wrong EPSG code used as suggested default?

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/GeoPose#21]
In https://www.ogc.org/projects/groups/geoposeswg 

under _Flexibility in the geographical frame of reference for GeoPose_

You have

> A consideration will be made to use WGS84 (EPSG 4389) as a default CRS if none is given in the data. 

As far as I can see from the [EPSG dataset](https://epsg.org/home.html) there is no CRS 4389.  The code is only used to describe the extent for Kyrgyzstan - east of 79°01'E

What default CRS is intended? 4326 / 4978

**Comment by 3DXScape** [comment]
You are correct - should be 4326. Will update text.
