### ISSUE TITLE
Adding pdf build instructions to the readme

### ISSUE THREAD

**Issue by nicolas-heigvd** [opengeospatial/GeoPose#26]
As a newcomer or a person who has no affinity with AsciiDoc,
I would like to have detailed build instructions (for each of the main platforms MacOS/Windows/Linux) on how to generate the pdf files from the raw material of this repo (or an external link to such instructions),
so that I can generate these pdf locally to check my changes before opening a pull request.

**Comment by 3DXScape** [comment]
[AsciiDoctor](https://asciidoctor.org/) will build PDF or HTML. You can preview your results without building a PDF in an AsciiDoc editor. There are lots of free choices, including VS Code.

**Comment by cperey** [comment]
Christine will ask OGC staff to provide the exact instructions.

**Comment by cperey** [comment]
Josh: the template is getting updated (next month will be PanDoc). 

Two possibilities: 
1. ask Bloomington to include the GeoPose repo to build every night/every 24 hours
2. run the asciidoctor on your computer (run the script on your local copy of the repo) then push updated doc to the repo
Nicolas: just looking for documentation to generate local PDF

Involves Ascii doctor and bibTech on your machine. 

Action: Josh to put the commands (run from terminal) on the GeoPose repo

**Comment by nicolas-heigvd** [comment]
Just a thought; if GeoPose it's not the only SWG to use ascii doc files, maybe it might be helpful to have a common and OGC-centralized place to share this information and then to only have a link to this place in each and every SWG?

**Comment by 3DXScape** [comment]
Every time that the adoc versions are updated, I have been generating new PDF and HTML versions before I merge a pull request or push to the main/master branch. Having OGC build is redundant and will not meet Nicolas' request for ability to check local changes. In addition, Only adoc or md files (plus any referenced images) should be pushed to GitHub: the PDF and HTML versions should all be derived using the same toolchain from the adoc files.

OGC uses AsciiDoctor when they do builds for SWGs. Some SWGs have additional scripts or add-ins (for math and drawing support, for example) that run as part of the build prior to piping output to AsciiDoctor. Other SWGs have created a top-level _tools_ folder to hold the scripts used by that SWG

For local use, I suggest the simple

_asciidoctor -r asciidoctor-pdf --trace -b pdf -o geopose_standard.pdf geopose_standard.adoc_

That works for the existing document content. There are some errors, but those reflect the editing status of the doc. As part of the resolution, I added a **tools** folder to the repo with scripts that OGC or anyone can use to generate their own PDF or HTML versions for the purpose of validating their adoc edits. I expect to add some math content so the scripts will change when the requirements change.

**Comment by 3DXScape** [comment]
Done.
