### ISSUE TITLE
Make the position variable `h` intrinsically carry a little more information?

### ISSUE THREAD

**Issue by nicolas-heigvd** [opengeospatial/GeoPose#27]
Hello,

as a future GeoPose user/developer, 
I want the positional variable describing the ellipsoidal height to carry the same level of information _by itself_ as the two others,
so that I don't have to dig into the specifications or unravel the JSON schema to remember its meaning when developing.

<br>
Indeed, when watching at Steve's great presentation during the developer track during the 119th OGC Member Meeting, I more and more have the feeling that this single `h` letter for describing the ellipsoidal height doesn't carry enough information compared to both `lat` and `lon`. in fact, when a (gis-)person read `lat` and `lon`, he or she will almost immediately know it's related to an ellipsoid, especially the WGS84 ellipsoid. 

I know `h` is actually commonly used in geodesy, but it's an "unfortunate" heritage and this single letter is too vague imho, its semantics is too "loose". This is also certainly the reason for Joana's request for clarification on its actual meaning during Steve's presentation (this kind of repeated reactions is actually the trigger that made me open this thread, because we may encounter this situation again in the future).

That's why I ask if we shouldn't make this variable carry _a little more_ information, for example by calling it `ell_h`, `ellh` or `hae` (...) so that it roughly matches the level of information carried by `lat` and `lon`? This way, one can say in a few milliseconds after glancing at this variable: "OK, this height is related to an ellipsoid. (and as `lat`and `lon` are related to the WGS84 ellipsoid, the height must also relate to this one)".

**Comment by 3DXScape** [comment]
I think having the structure be self-evident to the developer is a good goal. We seem to hit a wall in our discussions whenever the term has a meaning: elevation, altitude, height all seem to mean slightly different things to different people and the people have different levels of acceptance of their less-favoured terms. In its favour, h is good symbol because of it's history in geodesy. _hae_ is also from geodesy and surveying and it is very specific about its meaning. Probably few "normal" developers would know what _hae_ means but it would be a step in the direction of self-explanatory.

**Comment by 3DXScape** [comment]
And there is probably no other meaning for _hae_ (well I did a Google search and got tons of "hereditary angioedema" so maybe no other meaning in a geo context) so it would not suffer from imprecision of meaning or multiple interpretations. If a person did not know what it is, they are not likely to assign some incorrect meaning but instead would find the definition we intend. It is frustrating that the vertical definition is as simple as it appears.

**Comment by 3DXScape** [comment]
...is **not** as simple as it appears.

**Comment by cperey** [comment]
SWG discussed on July 16 and agreed to leave "h" as is.
