### ISSUE TITLE
Integrating GeoPose in an exsting REST API to serve 3D position and orientation values 

### ISSUE THREAD

**Issue by nicolas-heigvd** [opengeospatial/GeoPose#28]
As a web developer working with 3D features,

I would like to integrate a `/geopose` endpoint to my existing [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API,

in order to share 3D position+orientation values for any features, for example: `/collection/{collection_id}/feature/{feature_id}/geopose`
_and/or_
having this geopose as an embedded attribute of a more complex JSON response describing any feature, e.g. when fetching another endpoint: `/collection/{collection_id}/feature/{feature_id}/attributes`. This endpoint must serve the geopose along other parameters or metadata which can also be filtered using additional query parameters. This is typically the case when you work with images which may have plenty of other geometrical parameters and other metadata such as those defined in [EXIFs](https://www.cipa.jp/std/std-sec_e.html), [XMP](https://www.adobe.com/products/xmp.html) or [IPTC](https://iptc.org/) + many others, and for which you want to extract a subset.
Such query parameters should also apply for filtering out features based on the position or any given angular value _from_ the geopose object itself.
 
To this end, I already have some features in a PostGIS database having a WGS84 (or any other known CRS) position along with some triplet of angular values, defined as yaw, pitch and roll according to an internal structure, for which we may (or may not in the luckiest case) have to do some transformations so that they comply with the definition of 3D orientations in the GeoPose standard. In case they do not comply, I wish I can _check_ in a easy and convenient way if the transformations I have done are actually giving a correct geopose according to the standard.

In relation to all this, a tighter integration with the OGC APIs may be a nice to have.

🚀👍🏼

**Comment by 3DXScape** [comment]
1. Yes, a future GeoPose API should probably follow the evolving OGC REST API pattern
2. For the encoded GeoPose data objects, there is already the possibility to use the validation API documented at (https://service.geopose.io/solar/swagger) to check syntactic correctness, including the generic request  (https://service.geopose.io/solar/geopose/validate/any). This will be rolled into the OGC compliance testing in some form when the GeoPose data standard is published. 
3. But I think you are referring to the correctness of the transformation component *values*.
4. If so, can you give some example of how this could be structured? Simple testing of the validity of the numerical values could easily be added to the existing validation endpoints. Range testing of values is obvious. Also there are some joint constraints on values such as the components of unit quaternions. Testing whether two GeoPoses are effectively the same (e.g. a YPR and a quaternion version of the same GeoPose) would be a structural addition that I can foresee.

**Comment by 3DXScape** [comment]
Scoped for later. Closed for now.
