### ISSUE TITLE
Text-based Sequential Value Representation for GeoPose

### ISSUE THREAD

**Issue by MikelSalazar** [opengeospatial/GeoPose#29]
As we discussed last Friday (July 9th), one of the things I believe would be very useful in the short term is the ability to represent GeoPoses (at least the basic options) as a sequence of values so that we can serialize them into simpler string representations (like CSV, PHP array notations, URI parameters, etc). In this way, it would be possible to encode the GeoPose data much easier in web environments (using either [GET or POST parameters](https://www.w3schools.com/tags/ref_httpmethods.asp)). 

The main issues that we have to address to create this representation would be:

1.  Defining a specific order of the different attributes (for example, saving the angles in Yaw-Pitch-Roll order because Yaw is usually more relevant in most use cases),
2. The maximum number of decimals for the numeric values (if any).
3. Whether to include a initial value to indicate the type of GeoPose that it is going to be defined afterwards or to determine the type by the number of values provided.
4. Whether or not to allow incomplete definitions (where the values not provided are replaced by default values).
5. What separator character to use when a comma can not be used (like in URLs).
6. What separator character to use to concatenate multiple GeoPoses (in most CSV encodings, it is the new_line character, but that might be also not be available in single-line strings, such as URLs).

As an example, instead of having to write....
`index.php?latitude=52.4765&longitude=12.657&h=45&pitch=12.5&roll=56&yaw=42`

...we can just write the same data like this: 
`index.php?geopose=52.4765,12.657,45,42,12.5,56`
(please note that the values for the angles have been rearranged to fit the proposed Yaw-Pitch-Roll order).

**Comment by cperey** [comment]
Robotic Operating System (ROS) has an order defined. Can we consider that as an order for GeoPose? 

What will be included to express the "type" of GeoPose is encoded? 

Steve: There's Basic (purely numbers), the others have text, some of which can be quite long. So, only Basic GeoPose only have numbers.

JE: Should there be one for Quartenion and other for YPR and then don't have to specify in the file?
JM: suggest not have a "type" field. If connecting to a stream of data you might miss the "top of the file". Make it easier to access streams as opposed to headed files. 
MS: We can concatenate 
SS: we could add a new encoding in the document, something like CSV or delimited numeric values. 
Mikel will look into both options and create a table with pros and cons.

**Comment by 3DXScape** [comment]
Scoped for later. Closed for now.
