### ISSUE TITLE
Ideas for how OGC API - Features could leverage GeoPose (Jerome St-Louis)

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPose#33]
This issue is the body of an e-mail sent by Jerome St-Louis on Sept 9, 2021

First I think we need to make the distinction between the more abstract concept of a GeoPose, and then the particular GeoPose JSON encoding.
I think the former is more relevant to OGC API - Features than the latter, as GeoJSON used in Features already prescribes a mechanism to describe positions through the geometry property of its features.

One use we already make of a GeoPose (at least at the conceptual level) is instantiation of referenced 3D models such as buildings or trees in 3D datasets.
Each building and tree has a position, and in some cases an orientation as well.
Orientation is more useful for geotypical models like trees where a forest can be built out of just a few models but tweaking orientation and/or scaling for things to look more natural.

Since the GeoJSON geometry property already provides the latitude, longitude and height, we only need to add the orientation (as 'yaw', or optionally as yaw/pitch/roll if the additional degrees of freedom are desired) as GeoJSON properties for the features.

An implementation of this in our OGC API - Features implementation is found here:

https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Buildings
https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Trees

e.g.

https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Trees/items/1.json
https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Buildings/items/1.json

The position is in the geometry, and the "model::orientation" stores a Yaw,Pitch,Roll orientation.
The corresponding original orientation property from CDB 1.x is also included (AO1).

Notice that the tree feature can be a MultiPoint instantiating multiple trees using the same models,but only for instances having the exact same orientation,because the orientation is stored in a property and properties are per-feature rather than per point,

The 3D models being "GeoPosed" are referenced by the "model::id" property for which e.g. a glTF model can be downloaded using that ID:

    https://gltf-viewer.donmccurdy.com/#model=https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Trees/models/1207959553.glb

    https://gltf-viewer.donmccurdy.com/#model=https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Buildings/models/1744830465.glb

This concept of positioning & orienting 3D models is also used:

- in CDB 1.x,
- in the proposed GeoPackage extension for 3D Models ( https://github.com/ecere/geopackage/tree/master/spec/3d-models ),
- will likely be used again in CDB 2 that may use that GeoPackage extension,
- is described in the 2DTMS informative annex on multi-dimensional content ( https://docs.opengeospatial.org/DRAFTS/17-083r3.html#_point_features_instantiating_3d_models ),
- and will likely be one mechanism to distribute 3D content in GeoVolumes extending the Tiles API to 3D following that approach.

I believe all of this is much in line with GeoPose, in that it includes both a position and orientation, and the 3D orientation is relative to the plane tangent to the surface of the Earth at that position.

I'm not 100% sure whether the signs of the YPR angles follow the GeoPose specification, we could verify.
The yaw angle is usually positive clockwise from the North, not sure about pitch & roll.

Another potentially interesting toipc to explore is how to use GeoPose for per-point orientation and/or scale factors for a multi-point feature, such an oak-forest re-using the same geo-typical oak tree model, might potentially be an extension of interest for Features & Geometry JSON.

This would allow per-point full GeoPoses inside a single MultiPoint feature.

--------------------------

Additional background and context would also be found in the following documents:

- OGC Testbed-14: CityGML and AR Engineering Report ( https://docs.ogc.org/per/18-025.html )

- Interoperable Simulation and Gaming Sprint Engineering Report ( http://docs.ogc.org/per/20-087.html )

- ISG Year 2 ER ( https://github.com/opengeospatial/OGC-ISG-Sprint-Sep-2020/tree/master/Sprint%20Report -- not yet published )

- GeoVolumes charter ( https://portal.ogc.org/files/97171 )

**Comment by cperey** [comment]
Notes during Sept 14 meeting

Clemens P: what is described in GeoPose spec is JSON encoding. Could be embedded in feature data. 

Please clarify if this is not the case.

Two extensions to Features API could be envisaged: 
1. OGC Features doesn't have a mandatory encoding. GeoJSON, others are possible 
 Need to come up with a Feature encoding with GeoPose elements

2. What feature, by definition, supports is searches on location and temporal aspects. 
- GeoPose also has viewpoint/port and other aspects. 
- If we want to have searches on those aspects there would need to be extensions.

Jerome St-Louis comment: 
The one use case, rather than trying to add the extension. 
The GeoPose could be some information that's part of the metadata (??)

One of the ways that a ??? stores data is that each of the models is in a specific position, or one geospatial model (orientation is usually already included in the model).

**Comment by cperey** [comment]
Notes during Sept 14 meeting

I don't thnk scaling is a property in GeoPose, but otherwise the concept is similar. 

Clemens: if that is the idea, then the standard could be improved by separating the requirements classes and the conformance classes. 

Relevant to this and also to next version of CDB, and also GeoPackage for 3D models. 

Steve Smyth: to add, there is an intermediate level of specifications called "Structural Data Units" they are separated out already specifically, so that the logical model for which the JSON is available is also possible. 

Clemens: Still you should separate JSON encoding to a separate requirements class. In the same requirements class as the logical model. 

Steve: we can split that and it's a good suggestion.

**Comment by cperey** [comment]
See https://maps.ecere.com/ogcapi/collections/SanDiegoCDB:Trees/items/1.json 

Features API doesn't do everything. Features knows about location and temporal data. And you can query those, but the specific orientation and view, etc is not part of Features API. There's no intrinsic way to query orientation. 

So that is a key element that is not in Features API that GeoPose fills. 

There's the GeoPose of the viewer and the GeoPose of the objects in the world. 

the GeoPose of the viewer is one or a few positions. But with 3D clients you want very rapid response, so to query for every single time you turn your head is not practical. So the data may be queried using Tiles.

**Comment by cperey** [comment]
Mikel: The problem with adding a scale factor to a "Pose", is that it technically becomes a "Transform" (which is not a bad thing per se... but then it is no longer a pose).

Jerome: not suggesting to add scale to a pose, but if you have an object and want to place it in the world. The transform is the GeoPose + the scale, maybe.

**Comment by cperey** [comment]
Is there anything to be done? And by whom?

GeoPose SWG could work on API building blocks to filter data based on these other aspects not currently covered by Features (e.g., view angle) and other physical aspects that are beyond location in space and time. 

It's what 3D Portrayal service was supposed to do. 

Because 3D is often a lot of data and you need high response rate. Typically have a data selection (e.g. Tiles). this is why in a real time client this might not be very useful. But if data can be queried, this may not be a suitable way to request 3D data in real time.

And in the OGC, we could see where it ends up.

**Comment by cperey** [comment]
Steve: really helpful to understand how we can fit in with Features. A lot of new value in the idea of query on features that are viewed by a sensor, as opposed to the location of the sensor at the time of capture. We will digest. Continue discussion... 

Jeremy: we would have to think about is whether the position and orientation (look at direction) is sufficient, or if you need info about view frustum/ cone would be useful. 

Jerome: there is value in discovery from the GeoPose, but at 90 fps, it's probably not a use case, low value. But there are other use cases. 

Steve: in content in creation, this could be useful.

**Comment by cperey** [comment]
Nicolas proposed that issue #28 is also relevant 
https://github.com/opengeospatial/GeoPose/issues/28

**Comment by 3DXScape** [comment]
This is not on the path to final adoption of the v 1.0 standard but important nevertheless. We should discuss what we want to do here.

**Comment by 3DXScape** [comment]
The separation of logical definition of  implementation-neutral target data objects and their serialization in an encoding is now clarified in the informative text. The remainder of this comment thread relates to future development of GeoPose.
