### ISSUE TITLE
Editorial comments from a review on 2021-10-07

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/GeoPose#38]
Comments from the review of the [draft GeoPose](https://portal.ogc.org/files/?artifact_id=98795) specification on 2021-10-07.

- [x] Several figures are missing captions throughout the document.
- [x] Page 6: Abstract Section header appears to have “cd ..\..” as a prefix. 
- [x] Page 8: Section vii appears to end with …
- [x] Page 10: Add link to OGC Compliance Testing Policies (https://portal.ogc.org/files/?artifact_id=55234) and to OGC Compliance Testing website (https://www.ogc.org/compliance).
- [x] Page 10: Change “OGC® interface standard”  to “OGC® Standard”. 
- [x] Page 12: Formatting of Chapter 3 needs fixing.
- [x] Page 19: Section 5.2.1 is blank.
- [x] Page 33: The text YPR is floating on the page, i.e. it is not part of any paragraph. I think this was meant to be a section header for Yaw-Pitch-Roll.
- [x] Page 34: Typo “oThe”
- [x] Section 7.3: Several requirements have descriptions that stop mid-sentence e.g. Requirements AD-S-1, Graph-S-1 , Chain-S-2, and Regular_Series-S-1. Several other requirements  in Section 7.3 have the same issue.
- [x] Section 7.4: Some of the sub-headers appear to be missing numbers. Also related, some of the sub-headers in this section could be turned into Listing captions. 
- [x] Annex A: Some sections appear to have titles beginning with a period (.)  
- [x] Annex A.2: The header title begins with a (+). 
- [x] Annex A: There are several requirements that do not appear to be tested by any of the abstract tests.
- [x] Annex H: Remove the example content from the Bibliography and fix formatting of the “On quaternions..” reference.

**Comment by 3DXScape** [comment]
There are still two items to complete. This is taking some trial and error to get everything into line.

**Comment by 3DXScape** [comment]
Resolved as requested
