### ISSUE TITLE
Comment on Draft v1.0 OGC doc 21-056r4

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/GeoPose#39]
Corrections required to Chapter 3 (references):

1. Correct the URI for EPSG to https://epsg.org

2. In the coordinate reference system entry, remove the link to Wikipaedia https://en.wikipedia.org/wiki/Spatial_reference_system as much of the content is not correct, for example (i) an SRS is not a CRS, (ii) none of the examples are coordinate reference systems, (iii) the WKT given is not compliant with ISO 19162, (iv) some of the external links should not be condoned/endorsed in an OGC specification and (v) others (e.g. EPSG) are wrong/broken

**Comment by 3DXScape** [comment]
Changed as indicated in the original comment.
