### ISSUE TITLE
Quaternion property

### ISSUE THREAD

**Issue by michaelvogt** [opengeospatial/GeoPose#4]
This might not be considered an issue, it's more about consistency. 

In 7.4.1 basic-quaternion, the property for the quaternion is 'quaternion'. 
In 7.4.2 basic-euler, the property of the euler angles is 'rotations'.

Then from 7.4.4 on, the property name for quaternions is 'rotation'. This gives me the impression, that the value is euler angles.

Having consistent property names for quaternions and a different property name for euler angles (for example 'angles') would remove such confusion.

**Comment by 3DXScape** [comment]
Good catch. It should always be quaternion for quaternions and rotations for Euler angles. This is an internal consistency issue. 
Proposed resolution: edit the text to reflect the issue as raised.

**Comment by 3DXScape** [comment]
Updated schemata in documents.

**Comment by 3DXScape** [comment]
No further comments so closed as resolved per previous comments.
