### ISSUE TITLE
Two-Dimensional GeoPose

### ISSUE THREAD

**Issue by rjksmith** [opengeospatial/GeoPose#6]
**Question:** Has two dimensional GeoPose been considered?

WebVMT only _requires_ two-dimensional co-ordinates: longitude and latitude. Can GeoPose handle this reduced complexity?

**Comment by 3DXScape** [comment]
This is in some plane in the outer reference frame and the obvious one is one tangent to the ellipsoid at the given lat, lon on the ellipsoid. That's the most obvious vertical reference. Naively, we could just make "height" optional and then a missing height would be replaced by a 0 value. 

A related but different "2D" is in the inner frame. 2D here could imply that only the rotation about the Z axis would be present or vice versa. For a lot of applications where mobility is bound to a surface (for example surface ships or land vehicles) this is the important rotation - yaw or heading - except maybe in extreme circumstances.

We should probably have a discussion on optionality of height and rotations about the Y and X axes.

**Comment by rjksmith** [comment]
Yes, height is optional for WebVMT. My thought was to collapse the complexity to _latitude_, _longitude_ and _heading_ as you suggest.

On a wider point, I'm interested in how GeoPose defines '_height_'. For example, the difference between 'above ground level' and 'above mean sea level' is quite important in aviation.

**Comment by 3DXScape** [comment]
The meaning of "height" is defined by the choice of reference frame. AGL, ASL, and pressure altitude are valid choices for a vertical datum and ISO 19111/ISO 18162 are examples of how to express this.  It can be pretty cumbersome.

**Comment by 3DXScape** [comment]
We should discuss the possibility of making height optional. One logical way to do this (in my brain, anyway) is to also define a default value (could be 0 or "ground/water level") for "h" in the Basic GeoPoses. Somehow this makes me a little uneasy. Any discussion?

**Comment by rjksmith** [comment]
In a 2D use case, the height is (by definition) _undefined_ so setting any default value is misleading and needs to be properly discriminated from the 3D use case with the same height value.

This is highlighted by the [above/below horizon use cases](https://github.com/opengeospatial/GeoPose/issues/12#issue-855984769) in issue 12. In the below-horizon use case, the GeoPose intersects the ground so zero height makes some sense, though still assumes that the target object is on the ground and any errors in the 2D target location will propagate into the inferred height. The above-horizon use case is more prone to problems as identifying a target aircraft with zero height is likely to cause confusion at best.

**Comment by 3DXScape** [comment]
I thought some more about this issue and it seems to me that a 2D GeoPose would be embedded in some surface. This could be an ellipsoid, geoid, land surface, pressure altitude or any other surface that makes sense for the application.  The surface has no vertical coordinate. The surface could be defined via the CRS but this seems a little indirect.

**Comment by cperey** [comment]
Discussion of having h optional (so if no value, it is undefined.) But it was agreed that, for purpose of efficiency, any optional value adds an extra step.

Leaves some questions open (to be addressed in the future).

Resolution of the SWG is to consider this for GeoPose version 1.X
