### ISSUE TITLE
JSON representations for different types of rotation systems

### ISSUE THREAD

**Issue by MikelSalazar** [opengeospatial/GeoPose#8]
After evaluating the different issues relating to how to represent the rotations in GeoPose, I wanted to share a complete proposal to try to present a comprehensive solution for them.

### Problem statement:
There are three types of rotations systems, used in different use cases: Euler angles (simple, but require specifying the order of operations to avoid problems), quaternions (that are great to compute interpolations, but require 4 values and are difficult for humans to understand) and aircraft principal axes (that are intuitive, but mostly used in aerospace applications). While they are simply a collection of 3 or 4 numbers, depending on the use case (and if the user is a human being or a computer system), one system makes more sense than the others.

### Proposed solution:
To use both an array and a specific (object) definition of the elements for those who need more detail:
- Interoperable Array: Create an array of (floating-point) numbers called "rotation"  that  contains the numbers in a way that it is compatible for all use cases (and both for Euler Angles and Aircraft Principal Axes, the order is adjusted to account for the bigger relevance of the rotation on the vertical axis in most of those use cases).

**Array** | **Euler** | **Aircraft** | **Quaternion** 
-----  | ----- | ------- | ------------ 
  [0]   |    Z    |   Yaw   |     X     
  [1]   |    Y    |   Pitch  |    Y     
  [2]   |    X    |   Roll    |    Z    
  [3]   |  N/A  |   N/A  |    W   

- Object definition: If, for whatever reason, the creator of the GeoPose requires a more detailed specification of the rotation, he/she/it would be able to do so by specifying the rotation with an "object" property (with a specific name for each type). And if there is a component that is not specified, its value will default to 0.

**Type**  |  **Property Name** | **JSON definition**
-----  | ------- | ------- 
  Euler   |    "eulerAngles"    |   { "x": number, "y": number,  "z": number }  |
  Aircraft |    "aircraftAxes"    |   { "yaw": number, "pitch": number, "roll": number }  |
  Quaternion |    "quaternion"    |   { "x": number, "y": number,  "z": number,  "w": number  }  |

In this way it is possible to define rotations, without requiring implementers to program a lot of code to serialize and deserialize the GeoPose data (because this system is very similar to the methods already included in most 3D engines to convert between arrays and rotations, like in [Threejs ](https://threejs.org/docs/#api/en/math/Quaternion.fromArray) or [Unity](https://docs.unity3d.com/ScriptReference/Quaternion.Index_operator.html)).

Note: While only one of this two options will be required, in the strange case both systems are defined in a GeoPose, the object definition should be taken as the only valid one.

Note 2: While the proposed interoperable array allows the creators to reduce the number of components (because, in practice, most GeoPoses would probably only require the Z/Roll component) , if it is required to have a fixed side for the array, specific values (like 0xFFFFFFFF) can be used as padding at the end of the array (while also allowing an easy separation between quaternions and other rotation systems).

**Comment by 3DXScape** [comment]
Had discussion 9 July . Mikel will create new issue.
