### ISSUE TITLE
Missing text for clause 5.2 in specification

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPose#82]
See screenshot taken from https://docs.ogc.org/is/21-056r11/21-056r11.html#toc22

<img width="1397" alt="Screenshot 2024-04-09 at 1 39 19 PM" src="https://github.com/opengeospatial/GeoPose/assets/5149991/e0632b16-5c5b-4ade-9e92-5c3aca892e0b">

**Comment by 3DXScape** [comment]
Heading removed
