### ISSUE TITLE
Develop set of definitions for GeoPose

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPose#9]
We need to come up with a shared/agreed definition of GeoPose that can be used everywhere. 

I propose to do that development here on the About GeoPose .adoc 

https://github.com/opengeospatial/GeoPose/blob/main/About%20GeoPose.adoc

**Comment by theareaorg** [comment]
Discussed during April 16: GeoPose encodes the real world position and orientation of a real or a virtual object in a machine-readable form

**Comment by theareaorg** [comment]
@3DXScape can you please find the section of text in the standard with the definition of GeoPose and insert it here?

**Comment by 3DXScape** [comment]
The GeoPose 1.0 Standard defines requirements for the interoperable exchange of the location and orientation of real or virtual geometric objects (Poses) within reference frames anchored to the earth's surface (Geo). The Standard specifies a basic form with no configuration options for common use cases, an advanced form with more flexibility for more complex applications, and composite GeoPose structures to support time series, chain, and graph structures.

**Comment by 3DXScape** [comment]
Extracted from standard and simplified and added to web site. Done.
